default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
  stats:
    <<: *default
    url: <%= ENV['HYPERCABLE_STATS_DATABASE_URL'] %>

test:
  main:
    <<: *default
    database: 'hypercable_web_test'
  stats:
    <<: *default
    database: 'hypercable_stats_test'

production:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
  stats:
    <<: *default
    url: <%= ENV['HYPERCABLE_STATS_DATABASE_URL'] %>
