default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
    migrations_paths: db/migrate
  hyper:
    <<: *default
    url: <%= ENV['HYPERCABLE_HYPER_DATABASE_URL'] %>
    migrations_paths: db/hyper_migrate

test:
  main:
    <<: *default
    database: 'hypercable_web_test'
    migrations_paths: db/migrate
  hyper:
    <<: *default
    database: 'hypercable_hyper_test'
    migrations_paths: db/hyper_migrate

production:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
    migrations_paths: db/migrate
  hyper:
    <<: *default
    url: <%= ENV['HYPERCABLE_HYPER_DATABASE_URL'] %>
    migrations_paths: db/hyper_migrate
