default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
    migrations_paths: db/migrate
  olap:
    <<: *default
    url: <%= ENV['HYPERCABLE_OLAP_DATABASE_URL'] %>
    migrations_paths: db/olap_migrate

test:
  main:
    <<: *default
    database: 'hypercable_web_test'
    migrations_paths: db/migrate
  olap:
    <<: *default
    database: 'hypercable_olap_test'
    migrations_paths: db/olap_migrate

production:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
    migrations_paths: db/migrate
  olap:
    <<: *default
    url: <%= ENV['HYPERCABLE_OLAP_DATABASE_URL'] %>
    migrations_paths: db/olap_migrate
