default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
    migrations_paths: db/migrate
  stats:
    <<: *default
    url: <%= ENV['HYPERCABLE_STATS_DATABASE_URL'] %>
    migrations_paths: db/stats_migrate

test:
  main:
    <<: *default
    database: 'hypercable_web_test'
    migrations_paths: db/migrate
  stats:
    <<: *default
    database: 'hypercable_stats_test'
    migrations_paths: db/stats_migrate

production:
  main:
    <<: *default
    url: <%= ENV['HYPERCABLE_WEB_DATABASE_URL'] %>
    migrations_paths: db/migrate
  stats:
    <<: *default
    url: <%= ENV['HYPERCABLE_STATS_DATABASE_URL'] %>
    migrations_paths: db/stats_migrate
